"""add indexes to foreign key columns

Revision ID: 4b7c023c4487
Revises: 9dad9729d821
Create Date: 2026-03-14 18:58:48.663671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7c023c4487'
down_revision = '9dad9729d821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_userID'), ['userID'], unique=False)
        batch_op.drop_column('category')

    with op.batch_alter_table('shared_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_inventory_ownersID'), ['ownersID'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_inventory_sharedID'), ['sharedID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_inventory_sharedID'))
        batch_op.drop_index(batch_op.f('ix_shared_inventory_ownersID'))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_inventory_userID'))

    # ### end Alembic commands ###
